---
title: "FRM_Midterm_Project_1 Equal Weights Model Based approach"
output: html_document
---


```{r}
#library("forecast")
#library("tseries")
library("gridExtra")
library("ggplot2")
library("FKF")
#library("zoo")
library(readxl)
library(data.table)
library(R.matlab)
library(MTS)
library(car)

```


```{r}
rm(list = ls())
```



DATA
```{r}

GEdata <- read.csv("GEData.txt",sep= ",", header = TRUE)
UKdata <- read.csv("UKData.txt", sep = ",", header=TRUE)
USdata <- read.csv("USData.txt", sep = ",", header= TRUE)

```


```{r}

#Germany: BMW.DE , DBK.DE
#United kingdom: RSA.L , LRE.L
#USA : COST, FDX, IBM, XOM, DIS, APPL


eq_weights = seq(10**6, 10**6, length=10)


GE_list <- c("BMW.DE", "DBK.DE")
UK_list <- c("RSA.L", "LRE.L")
US_list <- c("COST","FDX","IBM","XOM","DIS","AAPL")
FX_names <- c("EURUSD.X", "GBPUSD.X")
Indices <- c("X.GDAXI", "X.FTSE", "X.DJI")

GE_data <- subset.data.frame(GEdata, select = GE_list)
UK_data <- subset.data.frame(UKdata, select = UK_list)
US_data <- subset.data.frame(USdata, select = US_list)

FX_data_1 <- subset.data.frame(GEdata, select = FX_names[1])
FX_data_2 <- subset.data.frame(UKdata, select = FX_names[2])

Index_GE <- subset.data.frame(GEdata, select = Indices[1])
Index_UK <- subset.data.frame(UKdata, select = Indices[2])
Index_US <- subset.data.frame(USdata, select = Indices[3])
Index_rates <- cbind(Index_US, Index_GE, Index_UK)



```



Dates
```{r}
dates <- fread("USdata.txt", select = c("Year","Month","Day"))
GEdata$date <- as.Date(with(dates, paste(Year, Month, Day,sep="-")), "%Y-%m-%d")
UKdata$date <- as.Date(with(dates, paste(Year, Month, Day,sep="-")), "%Y-%m-%d")
USdata$date <- as.Date(with(dates, paste(Year, Month, Day,sep="-")), "%Y-%m-%d")

date <- USdata$date
```

Merging data
```{r}
Stocks <- cbind(date,US_data,GE_data,UK_data)
FX_rates <- cbind(date,FX_data_1,FX_data_2)
Index_rates <- cbind(date,Index_GE, Index_UK)
stock_names <- colnames(Stocks)
```



Converting GE and UK to USD

```{r}

Stocks_converted <- Stocks
Stocks_converted[,8:9] <- Stocks[,8:9]*FX_rates$EURUSD.X
Stocks_converted[,10:11] <- Stocks[,10:11]*FX_rates$GBPUSD.X

```

```{r}
Stocks_converted
```




```{r}

plot(Stocks_converted$date, Stocks_converted$COST/Stocks_converted$COST[1], 
     col = 1, 
     lty = 1, 
     type = "l", 
     ylim=c(0,21), 
     xlab = "Date", 
     ylab="Price",
     main="Standardized stock prices in USD")

for (i in 3:11){
  lines(Stocks_converted$date, Stocks_converted[,i]/Stocks_converted[,i][1], col = i-1, lty = 1, type = "l")
}

legend("topleft", legend = c(stock_names[2:11]), col = c(1,2,3,4,5,6,7,8,9,10), lty = c(1,1,1,1,1,1,1,1,1,1), cex = 0.5)



```





X.GDAXI = Germany index
X.FTSE = UK index
X.DJI = US index


Comparing the performance of stocks compared to the corresponding index in USD
```{r}

plot(Stocks_converted$date, (Stocks_converted$BMW.DE/Stocks_converted$BMW.DE[1]), col = 1, lty = 1, type="l", ylim=c(0,5), 
     main = "Germany",
     xlab = "Dates",
     ylab = "Stock performance")
lines(Stocks_converted$date, (Stocks_converted$DBK.DE/Stocks_converted$DBK.DE[1]), col = 2, lty = 1, type="l")
lines(Stocks_converted$date, (Index_rates$X.GDAXI*FX_rates$EURUSD.X/(Index_rates$X.GDAXI[1]*FX_rates$EURUSD.X[1])), col = 3, lty = 1, type = "l")
legend("topleft", legend = c("BMW", "DBK", "GDAXI"), col = c(1,2,3), lty =c(1,1,1),cex=0.8)


```

UK
```{r}
plot(Stocks_converted$date, (Stocks_converted$RSA.L/Stocks_converted$RSA.L[1]), 
     col = 1, 
     lty = 1, 
     type = "l",
     xlab = "Dates",
     ylab = "Stock performance",
     main = "UK",
     ylim = c(0,2.5))
lines(Stocks_converted$date, (Stocks_converted$LRE.L/Stocks_converted$LRE.L[1]), col = 2, lty = 1, type = "l")
lines(Stocks_converted$date, (Index_rates$X.FTSE*FX_rates$GBPUSD.X)/(Index_rates$X.FTSE[1]*FX_rates$GBPUSD.X[1]), col = 3, lty = 1, type ="l")
legend("topleft", legend = c("RSA.L", "LRE.L", "X.FTSE"), col = c(1,2,3), lty =c(1,1,1), cex = 0.8)




```



```{r}
plot(Stocks_converted$date, Stocks_converted$COST/Stocks_converted$COST[1], col = 1, lty = 1, type = "l",
     main = "USA",
     ylab = "Stock performance",
     xlab = "Dates",
     ylim = c(0,21))
lines(Stocks_converted$date, Stocks_converted$FDX/Stocks_converted$FDX[1], col = 2, lty = 1, type = "l")
lines(Stocks_converted$date, Stocks_converted$IBM/Stocks_converted$IBM[1], col = 3, lty = 1, type = "l")
lines(Stocks_converted$date, Stocks_converted$XOM/Stocks_converted$XOM[1], col = 4, lty = 1, type = "l")
lines(Stocks_converted$date, Stocks_converted$DIS/Stocks_converted$DIS[1], col = 5, lty = 1, type = "l")
lines(Stocks_converted$date, Stocks_converted$AAPL/Stocks_converted$AAPL[1], col = 6, lty = 1, type = "l")
lines(Stocks_converted$date, USdata$X.DJI/USdata$X.DJI[1], col = 7, lty = 1, type = "l")
legend("topleft", legend = c("COST", "FDX", "IBM", "XOM", "DIS","AAPL","X.DJI"), col = c(1,2,3,4,5,6,7), lty =c(1,1,1,1,1,1,1), cex = 0.8)
```


```{r}
plot(FX_rates$date, FX_rates$EURUSD.X/FX_rates$EURUSD.X[1], col = 1, lty = 1, type = "l",
     main = "EURUSD.X",
     ylab = "Exchange rate",
     xlab = "Dates",
     ylim = c(0.5,1.5))
lines(FX_rates$date, FX_rates$GBPUSD.X/FX_rates$GBPUSD.X[1], col = 2, lty = 1, type = "l")
legend("topleft", legend = c("EURUSD.X", "GBPUSD.X"), col = c(1,2,3,4,5,6,7), lty =c(1,1,1,1,1,1,1), cex = 0.8)
```



```{r}

returnCalc <- function(x){
  diff(x)/x[-length(x)]
}
```


```{r}

n <- nrow(Stocks)
Stock_returns <- matrix(NA,nrow=n-1, ncol = 11)


for (i in 2:11){
  Stock_returns[,i] <- returnCalc(Stocks_converted[,i])
}

#### Matching stocks with corresponding stock names
Stock_returns <- data.frame(Stock_returns)
Stock_returns[,1] <- Stocks$date[2:n]
names(Stock_returns) <- stock_names

```

Computing average yearly returns 
```{r}

Stock_hist_ave <- matrix(NA, nrow = 1, ncol = 10)

for(i in 2:11){
  #Daily average return
  Stock_hist_ave[1,i-1] <- sum(Stock_returns[i])/(n-1)
  #Daily average return converted to average yearly return
  Stock_hist_ave[1,i-1] <- (1+Stock_hist_ave[1,i-1])**252
  # Average yearly return -1 to get the %
  Stock_hist_ave[1,i-1] <- Stock_hist_ave[1,i-1]-1
}

Stock_hist_ave <- data.frame(Stock_hist_ave)
names(Stock_hist_ave) <- stock_names[2:11]
Stock_hist_ave

```


Annualizing the standard deviation
```{r}

Stock_annualized_SD <- matrix(NA,nrow=1,ncol = 10)
for(i in 2:11){
  Stock_annualized_SD[1,i-1] <- sd(Stock_returns[,i])
  Stock_annualized_SD[1,i-1] <- Stock_annualized_SD[1,i-1]*sqrt(252)
}

Stock_annualized_SD <- data.frame(Stock_annualized_SD)
names(Stock_annualized_SD) <- stock_names[2:11]

Stock_annualized_SD
```


#Calculating the correlation between stock returns - covariancee and daily standard deviation
```{r}
Stocks_cor <- cor(Stock_returns[,2:11])
Stocks_cov <- cov(Stock_returns[,2:11])
Stocks_daily_SD <- sqrt(diag(Stocks_cov))

```


```{r}
w <- rep(1/length(eq_weights),length(eq_weights))                         #equally weighted positions 
PF_variance <- eq_weights%*%Stocks_cov%*%eq_weights                       #variance of portfolio 

VAR99 <- qnorm(0.99)*sqrt(PF_variance)
ES99 <- sqrt(PF_variance)*exp(-qnorm(0.99)^2/2)/sqrt(2*pi)/0.01
VAR95 <- qnorm(0.95)*sqrt(PF_variance)
ES95 <- sqrt(PF_variance)*exp(-qnorm(0.95)^2/2)/sqrt(2*pi)/0.05

cat("Equal weights MBA: \n")
cat("99% VaR: ", VAR99, "\n")
cat("99% ES: ", ES99, "\n")
cat("95% VaR: ", VAR95, "\n")
cat("95% ES: ", ES95, "\n")
```

```{r}
#Value At Risk for exponentially weighted moving average (EWMA)

lambda <- 0.94
VariancesEWMA <- Stocks_cov
N <- length(Stock_returns$date)
HistoricalReturns <- data.matrix(Stock_returns[,2:11])

for (i in 2:N+1){
  VariancesEWMA <- lambda*VariancesEWMA + (1-lambda)*HistoricalReturns[i-1,]%*%t(HistoricalReturns[i-1,])
}

SD <-diag(VariancesEWMA)**0.5

PF_variance_EWMA <- eq_weights%*%VariancesEWMA%*%eq_weights
VAR99_EWMA <- qnorm(0.99)*sqrt(PF_variance_EWMA)
ES99_EWMA <- sqrt(PF_variance_EWMA)*exp(-qnorm(0.99)^2/2)/sqrt(2*pi)/0.01
VAR95_EWMA <- qnorm(0.95)*sqrt(PF_variance_EWMA)
ES95_EWMA <- sqrt(PF_variance_EWMA)*exp(-qnorm(0.95)^2/2)/sqrt(2*pi)/0.05

cat("EWMA MBA:\n")
cat("99% VaR: ", VAR99_EWMA, "\n")
cat("99% ES: ", ES99_EWMA, "\n")
cat("95% VaR: ", VAR95_EWMA, "\n")
cat("95% ES: ", ES95_EWMA, "\n")

```



```{r}
#Backtesting Equal weights

#calculate VaR for every day of 2020
windows <- ((2685-252):2685)
VAR99_EW_BT <- (1:252)
ES99_EW_BT <- (1:252)
VAR95_EW_BT <- (1:252)
ES95_EW_BT <- (1:252)

for (i in 1:252){
  #covariance matrix
  Stocks_cov <- cov(Stock_returns[i:windows[i],2:11])
  PF_variance <- eq_weights%*%Stocks_cov%*%eq_weights   
  VAR99_EW_BT[i] <- qnorm(0.99)*sqrt(PF_variance)
  ES99_EW_BT[i] <- sqrt(PF_variance)*exp(-qnorm(0.99)^2/2)/sqrt(2*pi)/0.01
  VAR95_EW_BT[i] <- qnorm(0.95)*sqrt(PF_variance)
  ES95_EW_BT[i] <- sqrt(PF_variance)*exp(-qnorm(0.95)^2/2)/sqrt(2*pi)/0.05
}


```


```{r}
#Backtesting EWMA MBA
VAR99_EWMA_BT <- (1:252)
ES99_EWMA_BT <- (1:252)
VAR95_EWMA_BT <- (1:252)
ES95_EWMA_BT <- (1:252)

for (i in 1:252){
  #covariance matrix for each window
  Stocks_cov <- cov(Stock_returns[i:windows[i],2:11])
  VariancesEWMA <- Stocks_cov
  
  #calculate EWMA variance matrix for each window
  for (j in (i+1):(windows[i]+1)){
    VariancesEWMA <- lambda*VariancesEWMA + (1-lambda)*HistoricalReturns[j-1,]%*%t(HistoricalReturns[j-1,])
  }

  SD <-diag(VariancesEWMA)**0.5
  
  PF_variance_EWMA <- eq_weights%*%VariancesEWMA%*%eq_weights
  VAR99_EWMA_BT[i] <- qnorm(0.99)*sqrt(PF_variance_EWMA)
  ES99_EWMA_BT[i] <- sqrt(PF_variance_EWMA)*exp(-qnorm(0.99)^2/2)/sqrt(2*pi)/0.01
  VAR95_EWMA_BT[i] <- qnorm(0.95)*sqrt(PF_variance_EWMA)
  ES95_EWMA_BT[i] <- sqrt(PF_variance_EWMA)*exp(-qnorm(0.95)^2/2)/sqrt(2*pi)/0.05
  
}

```



```{r}
#PnL every day of 2020

#add a column that would value an equally diverse portfolio of $10mm every day
Stock_returns$pf.value <- rep(NA,2685)

for (i in 1:2685){
  Stock_returns$pf.value[i] <- 10000000 + sum(Stock_returns[i,2:11]*eq_weights)
}
Stock_returns$PnL <- c((10000000-Stock_returns$pf.value[1]),rep(NA,2684))

Stock_returns$PnL[2:2685] <- Stock_returns$pf.value[3:2685]-Stock_returns$pf.value[2:2684]
```



```{r}
plot(Stock_returns$date[(2685-251):2685],Stock_returns$PnL[(2685-251):2685], type = "l", col = 1,
     main = "When the daily PnL exceeded the daily VaR [EW MBA]",
     xlab = "Date",
     ylab = "USD")
lines(Stock_returns$date[(2685-251):2685], -VAR99_EW_BT, col = 2, type ="l")
legend("topleft", legend = c("Daily PnL", "Daily 99% VaR"), col = c(1,2), lty =c(1,1), cex = 0.8)

```
```{r}
plot(Stock_returns$date[(2685-251):2685],Stock_returns$PnL[(2685-251):2685], type = "l", col = 1,
     main = "When the daily PnL exceeded the daily VaR [EW MBA]",
     xlab = "Date",
     ylab = "USD")
lines(Stock_returns$date[(2685-251):2685], -VAR95_EW_BT, col = 2, type ="l")
legend("topleft", legend = c("Daily PnL", "Daily 95% VaR"), col = c(1,2), lty =c(1,1), cex = 0.8)

```


```{r}
plot(Stock_returns$date[(2685-251):2685],Stock_returns$PnL[(2685-251):2685], type = "l", col = 1,
     main = "When the daily PnL exceeded the daily VaR [EWMA MBA]",
     xlab = "Date",
     ylab = "USD")
lines(Stock_returns$date[(2685-251):2685], -VAR99_EWMA_BT, col = 2, type ="l")
legend("topleft", legend = c("Daily PnL", "Daily 99% VaR"), col = c(1,2), lty =c(1,1), cex = 0.8)

```




```{r}
plot(Stock_returns$date[(2685-251):2685],Stock_returns$PnL[(2685-251):2685], type = "l", col = 1,
     main = "When the daily PnL exceeded the daily VaR [EWMA MBA]",
     xlab = "Date",
     ylab = "USD")
lines(Stock_returns$date[(2685-251):2685], -VAR95_EWMA_BT, col = 2, type ="l")
legend("topleft", legend = c("Daily PnL", "Daily 95% VaR"), col = c(1,2), lty =c(1,1), cex = 0.8)

```



```{r}
n_vio99_EW <- 0 
n_vio95_EW <- 0
PnL <- Stock_returns$PnL[(2685-251):2685]

for (i in (2:252)){
  if (-VAR99_EW_BT[i-1] > PnL[i]){
    n_vio99_EW <- n_vio99_EW + 1
  }
  if (-VAR95_EW_BT[i-1] > PnL[i]){
    n_vio95_EW <- n_vio95_EW + 1
  }
}

n_vio99_EW
n_vio95_EW

```




```{r}
n_vio99_EWMA <- 0 
n_vio95_EWMA <- 0

for (i in (1:252)){
  if (-VAR99_EWMA_BT[i] > PnL[i]){
    n_vio99_EWMA <- n_vio99_EWMA + 1
  }
  if (-VAR95_EWMA_BT[i] > PnL[i]){
    n_vio95_EWMA <- n_vio95_EWMA + 1
  }
}
```


```{r}

sigma_exp = 0.01
sigma_obs = n_vio99_EW / 252 # observed proportion of exceedances

test_statistic_LR_uc = ((sigma_exp**n_vio99_EW)*(1-sigma_exp)**(252-n_vio99_EW)) / ((sigma_obs**n_vio99_EW)*(1-sigma_obs)**(252-n_vio99_EW))
LR_uc_EW = -2 * log(test_statistic_LR_uc)

# Deny if 10% > 2.71 and at a 5% level, if LR_uc > 3.84
LR_uc_EW

test_statistic_LR_uc = ((sigma_exp**n_vio99_EWMA)*(1-sigma_exp)**(252-n_vio99_EWMA)) / ((sigma_obs**n_vio99_EWMA)*(1-sigma_obs)**(252-n_vio99_EWMA))
LR_uc_EWMA = -2 * log(test_statistic_LR_uc)
LR_uc_EWMA
```


```{r}



sigma_exp = 0.05
sigma_obs = n_vio95_EW / 252 # observed proportion of exceedances

test_statistic_LR_uc = ((sigma_exp**n_vio95_EW)*(1-sigma_exp)**(252-n_vio95_EW)) / ((sigma_obs**n_vio95_EW)*(1-sigma_obs)**(252-n_vio95_EW))
LR_uc = -2 * log(test_statistic_LR_uc)

# Deny if 10% > 2.71 and at a 5% level, if LR_uc > 3.84
LR_uc

test_statistic_LR_uc = ((sigma_exp**n_vio95_EWMA)*(1-sigma_exp)**(252-n_vio95_EWMA)) / ((sigma_obs**n_vio95_EWMA)*(1-sigma_obs)**(252-n_vio95_EWMA))
LR_uc_EWMA = -2 * log(test_statistic_LR_uc)
LR_uc_EWMA

```